# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FMDBMigrationDemo' do

pod 'FMDB', '~> 2.6'
pod 'FMDBMigrationManager', '~> 1.4.1'

end

