# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'iOS_Persistence_Performance_Compare' do

pod 'FMDB', '~> 2.6.2'
pod 'Realm', '~> 1.0.1'

end

