# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'BeeFrameworkDemo' do

pod 'BeeFramework', '~> 0.5.2'

end

