# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RESTKitTestDemo' do

pod 'RestKit', '~> 0.26.0'

end

